export const actionTypesMainData = {
    GET_MAIN_DATA: "GET_MAIN_DATA"
}

export const actionTypesPateints = {
    GET_PATEINT_DATA: "GET_PATEINT_DATA",
    GET_SINGLE_PATEINT_DATA: "GET_SINGLE_PATEINT_DATA",
    ADD_PATEINT: "ADD_PATEINT",
    DELETE_PATEINT: "DELETE_PATEINT"
}

export const actionTypesDoctors = {
    GET_DOCTOR_DATA: "GET_DOCTOR_DATA",
    GET_SINGLE_DOCTOR_DATA: "GET_SINGLE_DOCTOR_DATA",
    ADD_DOCTOR: "ADD_DOCTOR",
    DELETE_DOCTOR: "DELETE_DOCTOR"
}

export const actionTypesStaffs = {
    GET_STAFF_DATA: "GET_STAFF_DATA",
    GET_SINGLE_STAFF_DATA: "GET_SINGLE_STAFF_DATA",
    ADD_STAFF: "ADD_STAFF",
    DELETE_STAFF: "DELETE_STAFF"
}

export const actionTypesAccounts = {
    GET_ACCOUNT_DATA: "GET_ACCOUNT_DATA",
    GET_ACCOUNT_SINGLE_DATA: "GET_ACCOUNT_SINGLE_DATA",
    GET_ACCOUNT_ALL_DATA: "GET_ACCOUNT_ALL_DATA",
    ADD_TRX: "ADD_TRX",
}

export const actionTypesAppointment = {
    GET_APPOINT_DATA: "GET_ACCOUNT_DATA",
    GET_APPOINT_CATEGORY_DATA: "GET_APPOINT_CATEGORY_DATA",
    GET_APPOINT_DOCTOR_DATA: "GET_APPOINT_DOCTOR_DATA",
    GET_APPOINT_PATEINT_DATA: "GET_APPOINT_PATEINT_DATA",
    MAKE_DONE: "MAKE_DONE",
    ADD_APPOINT: "ADD_APPOINT"
}
